
services:
  frontend-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    volumes:
        - .:/app
        - /app/node_modules
    command: npm start
    ports:
      - "3000:3000"
  frontend-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile-prod
    ports:
      - "80:80"